### ISSUE TITLE
Plugin doesn't work?

### ISSUE THREAD

**Issue by mattcoxonline** [AMoreaux/Sketch-Icons#1]
I can successfully install the plugin, but the menu items don't do anything.

Sketch version 48.1
Mac OS 10.13.2

**Comment by valentinchrt** [comment]
Thanks for your feedback @mattcoxonline.
We are currently working on it.

**Comment by valentinchrt** [comment]
We just released the version 1.0.16, the issue is fixed normally!

Keep me informed @mattcoxonline :)

**Comment by mattcoxonline** [comment]
Thanks, @valentinchrt - will give it a shot when I'm back in the office tomorrow.
