### ISSUE TITLE
Add feature import icon as font and zeplin issue

### ISSUE THREAD

**Issue by redhajr** [AMoreaux/Sketch-Icons#10]
Using masking is good but there is issue when the artboard export to zeplin (color not read). Maybe if there is feature import as icon font the zeplin issue will be resolve. thanks

**Comment by AMoreaux** [comment]
Hi @redhajr if you use the mask from the color picker, the color will kept in zeplin. I may take it into account in the next release. But it's not a bug of the plugin, it's the Zeplin or Sketch's operation.

**Comment by redhajr** [comment]
how about import icon as font icon? optional import method

**Comment by valentinchrt** [comment]
Hey @redhajr, 

Thank you for you suggestion.
Unfortunately, it's not on our radar for a future release.

I recommend you to read this article if you want to manage font icons in Sketch:
https://medium.com/sketch-app-sources/the-perfect-sketch-icon-workflow-8d15bd5cc873

Valentin
