### ISSUE TITLE
Retype the size of icon when replace several icon

### ISSUE THREAD

**Issue by redhajr** [AMoreaux/Sketch-Icons#11]
when i wanna replace an icon, maybe ask again about the size of the icons

**Comment by AMoreaux** [comment]
I think when you use replace an icon, the new icon is smaller ? I will fixed in the next release. But I'm not sure to ask again to set a padding and size.

**Comment by redhajr** [comment]
yes, when i replace the icon is smaller. Retype icon size is useful when there are so much icon symbols with different size. thank you

**Comment by AMoreaux** [comment]
In the next version I keep the original padding of icons. When you replace an icon the new icon keep the original size. So the bug will be fixed in the next release.  But we don't want display a modal on "replace icons" feature.

**Comment by AMoreaux** [comment]
I closed. See #25
