### ISSUE TITLE
Wrong version number in manifest.json

### ISSUE THREAD

**Issue by bouchenoiremarc** [AMoreaux/Sketch-Icons#13]
3.0.14 can't be installed with Sketch's plugin updates because the .zip referenced in the `appcast.xml` has the wrong version number (3.0.12) in its `manifest.json`.

**Comment by AMoreaux** [comment]
Thanks. It's fixed. Can you confirm it work on your computer please ?

**Comment by bouchenoiremarc** [comment]
Not yet, only the repo's manifest appears to be changed, did you update the 3.0.14 release attached .zip?

**Comment by AMoreaux** [comment]
Sorry I updated one file out of two. Now it's good. Confirm?

**Comment by bouchenoiremarc** [comment]
Yep 😀
