### ISSUE TITLE
Can't get plugin to work for me

### ISSUE THREAD

**Issue by AndrewRodgers** [AMoreaux/Sketch-Icons#14]
Hey, I can't seem to get my icons to import _with_ a color mask, _nor_ converted to a symbol when using "from color picker". Maybe I'm just missing something? I'm linking to a video of me using the plugin along with attaching a zip of my test icons. Thanks in advance for any help, really want to get this working!
[sketch_icons_plugin_test_folder_02.zip](https://github.com/AMoreaux/Sketch-Icons/files/1626332/sketch_icons_plugin_test_folder_02.zip)
https://www.dropbox.com/s/m8jt61d0c4845ec/sketch_icons_help.mov?dl=0

**Comment by AMoreaux** [comment]
Hi @AndrewRodgers , which version of plugin and macos do you use ?

**Comment by AndrewRodgers** [comment]
I’m using 3.0.14, latest edition since you closed issue #13

**Comment by AMoreaux** [comment]
And the OS version ? Can you send me a screen of console. (see next image to open console)


<img width="763" alt="console open" src="https://user-images.githubusercontent.com/7237157/34880586-34883ce2-f7b1-11e7-97df-1e16c6005de7.png">

![console 2018-01-05 15-51-45](https://user-images.githubusercontent.com/7237157/34880595-39793c6a-f7b1-11e7-8aae-809bbbbd884c.png)

**Comment by AndrewRodgers** [comment]
Console Log: 
![image](https://user-images.githubusercontent.com/1911042/34890258-3815ee66-f79f-11e7-958f-d7cb56d6fd05.png)

OS Version: macOS Sierra v. 10.12.6

**Comment by AMoreaux** [comment]
Try to reinstall the plugin.

**Comment by dejot** [comment]
Same problem here. Reinstalling the plugin - manually or over sketch runner, doesn't make any difference. 
Thanks in advance.

**Comment by AMoreaux** [comment]
hi @dejot, you are on sierra or high sierra too ? Can you send me the log like AndrewRodgers please.

**Comment by dejot** [comment]
Hi @AMoreaux --> here you go
![2018-01-15_23-44-46](https://user-images.githubusercontent.com/1021447/34964515-402dc0e0-fa4e-11e7-9e47-0a0c842faac7.png)

**Comment by AMoreaux** [comment]
It may be a conflict between plugins. Can you disable all plugins except sketch-icons and retry please.

**Comment by dejot** [comment]
Hi @AMoreaux --> you're right!
It was one of the plugins. Since I'm not using all of them. I just activate these, I remeber i was using.

Thank's a lot...
If you want research about this problem, here's the list of all plugins I've downloaded to SKETCH:

![2018-01-16_00-56-26](https://user-images.githubusercontent.com/1021447/34965982-9d234978-fa58-11e7-9cb8-8c434c92834f.png)

**Comment by AndrewRodgers** [comment]
@AMoreaux - for what it's worth I reinstalled Sketch Icons, and then re-enabled All of the plug-ins that are checked below one-by-one (restarting and re-testing Sketch Icons as I went) and the one plugin that conflicted for me was [Sketch Focus](https://sketchfocus.com/)

![image](https://user-images.githubusercontent.com/1911042/34994489-a6b55762-faa1-11e7-9772-74bc366257a7.png)
![image](https://user-images.githubusercontent.com/1911042/34994506-b8b18062-faa1-11e7-9157-b9da462c758d.png)
![image](https://user-images.githubusercontent.com/1911042/34994528-cd3344e4-faa1-11e7-82db-081b0dd92dee.png)

**Comment by AMoreaux** [comment]
Thank you @AndrewRodgers  👍
