### ISSUE TITLE
Mask not working

### ISSUE THREAD

**Issue by marisnaylor** [AMoreaux/Sketch-Icons#15]
When importing icons or adding a mask to already-created icons, mask never applies. Running sketch 48.2 on mac.

**Comment by AMoreaux** [comment]
Hello, can you send me two icons of you set please ?

**Comment by marisnaylor** [comment]
@AMoreaux it was just standard font awesome icons. it doesn't work with any icons, though. Also doesn't convert them to symbols.

**Comment by marisnaylor** [comment]
@AMoreaux SOLVED after reading an old bug. Sketch Focus plugin was what was causing the issue. Uninstalled focus, re-installed icons. works great now. I would append the readme in case anyone else has this issue.

**Comment by valentinchrt** [comment]
Thanks for you feedback @marisnaylor!
