### ISSUE TITLE
Masks not being applied

### ISSUE THREAD

**Issue by llewellynathan** [AMoreaux/Sketch-Icons#16]
When I select one or many artboards and try to "Apply color mask..." masks are not applied. I'm using the latest version of Sketch and I'm on the latest Mac OS.

**Comment by valentinchrt** [comment]
Hey @llewellynathan, 

What kind of icon did you try? Filled or stroked?
If you can send me one or two icons of them, I will take a look

Thanks :)

**Comment by marisnaylor** [comment]
@valentinchrt I tried both and neither worked.

**Comment by marisnaylor** [comment]
@llewellynathan try disabling other plugins and reinstalling sketch icons. see if that fixes it.

**Comment by runnickrun** [comment]
Masks seem to work after disabling all plugins. So far works with the Runner.

**Comment by AMoreaux** [comment]
It seems that Sketch Focus plugin only is preventing Sketch Icons from working properly

**Comment by runnickrun** [comment]
@AMoreaux yep, I actually had Focus in place.
