### ISSUE TITLE
Sketch 48.2 (MacOS Sierra 10.12.6) work only import and replace icons

### ISSUE THREAD

**Issue by barmallion** [AMoreaux/Sketch-Icons#20]
Color masks don't work.
Can't create symbols (with checkbox in icon import modal).

**Comment by AMoreaux** [comment]
hi @barmallion can you send me two icons of you set and the log please ?
![image](https://user-images.githubusercontent.com/7237157/35123980-b0c3f7c2-fca4-11e7-9d1e-7bc979dd6527.png)
![image](https://user-images.githubusercontent.com/7237157/35123988-b825b3de-fca4-11e7-9300-14a3f5f0b780.png)

**Comment by barmallion** [comment]
Disabling all plugins work to me - thank you!
