### ISSUE TITLE
Feature request: multiple generate multiple sizes of the icon

### ISSUE THREAD

**Issue by runnickrun** [AMoreaux/Sketch-Icons#21]
It would be cool to have an ability to generate multiple sizes of the icon. Currently plugin allows only to create only one. 

![image](https://user-images.githubusercontent.com/18515722/35182580-91c18ca8-fde0-11e7-9a0d-f2697e046926.png)

For example, allow multiple fields for size or maybe a dynamic button “+ add size”.

**Comment by AMoreaux** [comment]
Thanks for you feedback. It's on the roadmap ! 👍

**Comment by AMoreaux** [comment]
hi @runnickrun  try the next release in beta. There is multiple size. (settings -> presets) https://www.dropbox.com/s/qmo8e1kq1ip6hvt/v4_sketch-icons_beta.zip?dl=0
Send me your feedback 😉
