### ISSUE TITLE
Path added to shape renders the icon into square

### ISSUE THREAD

**Issue by jluna79** [AMoreaux/Sketch-Icons#22]
Hi, I just installed the plugin (High Sierra, using sketch runner).

When I try to import the icons I am getting a very weird behaviour: Icons are smashed into a solid colour square.
![screen shot 2018-01-23 at 19 29 18](https://user-images.githubusercontent.com/411374/35293373-c7007f6a-0073-11e8-9783-2c43497772ef.png)

I reviewed the output and found that the problem is caused by a squared path that is added to the icon. 
![sketch-icons-bug](https://user-images.githubusercontent.com/411374/35293925-858d147e-0075-11e8-93ae-5f7dc24a9e7e.gif)

I have 100+ icons on this project so going one by one removing the Path is just impossible. Please help! :)

**Comment by AMoreaux** [comment]
hi, @jluna79 . Can you send me two icons of your set please ? You can also try with the next beta version : https://drive.google.com/drive/folders/1y05-V_X-d6U2Ag_xR2J_1Uk_Nghc2HVb?usp=sharing

**Comment by jluna79** [comment]
Hello,

I've been thinking about why it might be that the path is being added and I think it is because the icons have an overlaying mask (so that I can easily change the colour by using colour symbols) and this mask is being converted into a solid path (but it shouldn't).

Here's a screenshot of the structure of the icon and I'm attaching the two icons you requested.

![screen shot 2018-01-24 at 10 22 28](https://user-images.githubusercontent.com/411374/35324274-8ac2c774-00f0-11e8-8621-3cbe361bcc36.png)

[Icons.zip](https://github.com/AMoreaux/Sketch-Icons/files/1659264/Icons.zip)


Also, I saw in the readme file for the beta that `.svg` is being supported, so maybe this will fix it. I'll let you know. 

Thanks!

**Comment by AMoreaux** [comment]
Hello,
If you import without sketch-icons. Your icon are broken too. Because there is mask in your sources and sketch don't support import with mask.

**Comment by jluna79** [comment]
Mmmh, I didn't know that! :/

Btw, how are you importing the svg into sketch? If I drag&drop it into sketch or open the file I get the following result (which seems correct):

![image](https://user-images.githubusercontent.com/411374/35337374-4f11a922-011b-11e8-92bd-8a8cf46bb7da.png)

**Comment by AMoreaux** [comment]
🤔 When I drag and drop I see that : 

<img width="270" alt="screen shot 2018-01-24 at 15 35 34" src="https://user-images.githubusercontent.com/7237157/35337766-51a98884-011c-11e8-82c1-0219330f1b6d.png">

**Comment by jluna79** [comment]
That is very weird. This is what I see for that Icon:

![image](https://user-images.githubusercontent.com/411374/35339618-56ddaeb6-0121-11e8-9795-703e61c9d44a.png)

I'm using Sketch 48.2 (47327)

**Comment by AMoreaux** [comment]
Sorry I said stupid things. I had edit the source. Sketch work perfectly with mask.

**Comment by AMoreaux** [comment]
So. The problem is that the plugin don't work if there is mask in svg. I will work on this use case for next version.

**Comment by jluna79** [comment]
👍  I'll be waiting! :)

It's a very useful plug-in as it is, it can only get better and better!
