### ISSUE TITLE
Export icons function

### ISSUE THREAD

**Issue by rodnem** [AMoreaux/Sketch-Icons#26]
It could be extremely useful to be able to export a selection of icons using an inverse method of importing. I mean… I would like to be able to export without the color symbol applied to a shape mask. The shape used as mask then will have a variable hexadecimal color fill.

For example, in icomoon you can export your icons set with another color applied.

So then we would have cleaner svgs!

---
Perhaps it helps…
My friend @sandhose told me :
Launch the terminal, go to your assets folder et type :
sed -i ‘’ -e ‘/<rect /d’ ./*
It will remove from the svg file the line <rectangle …> used for the color.

**Comment by AMoreaux** [comment]
Hi @rodnem, I understand the problem but today I don't have time to develop this feature. If you know developers who could work on this feature I can help him.
