### ISSUE TITLE
Import icons as icon font

### ISSUE THREAD

**Issue by redhajr** [AMoreaux/Sketch-Icons#28]
some cases designer needs icon font ass assets not only svg

**Comment by valentinchrt** [comment]
Hey @redhajr,

Thanks for your feedback! Unfortunately, it's not the aim of Sketch Icons :)

If you want to work with an icon font, I recommend you to read this article:
[](https://medium.com/sketch-app-sources/the-perfect-sketch-icon-workflow-8d15bd5cc873)

👋
