### ISSUE TITLE
Errors for Import Icons

### ISSUE THREAD

**Issue by iansoper** [AMoreaux/Sketch-Icons#29]
When I try to import SVG files and apply a color mask, and convert to symbol, it is only importing the file, it is NOT applying a color mask, and NOT converting to a symbol. Here is the error I'm seeing in the Plugin Output console:

```
ERROR: TypeError: undefined is not an object (evaluating 'e.layers().reverse().forEach') «Plugin Output»
ArtboardChanged «Plugin Output»
```

**Comment by AMoreaux** [comment]
hi @iansoper , we know this bug. You can try with this version : https://drive.google.com/open?id=1y05-V_X-d6U2Ag_xR2J_1Uk_Nghc2HVb

**Comment by iansoper** [comment]
@AMoreaux I'm unable to download this, blocked. Can you attach directly?

**Comment by AMoreaux** [comment]
@iansoper : https://drive.google.com/open?id=1A9oHw2_0VvmErXElk_yLBJZJvuXmn9Te
