### ISSUE TITLE
Plugin not working and  removes the mask

### ISSUE THREAD

**Issue by redview13** [AMoreaux/Sketch-Icons#30]
Sketch 48.2 
Plugin suddenly stopped working. 
If there is a mask, the plugin deletes it when trying to replace or add it.

**Comment by xlanex6** [comment]
Sketch 48.2
Same for me.
no response on cmd + shift + i or by the menu.

no reaction

**Comment by AMoreaux** [comment]
Hi @xlanex6, try to disable others plugin. It may be a conflict with another plugin. By the way @redview13 we work on a new version to resolve some issue. Thanks for your reports 👍
