### ISSUE TITLE
Sketch 49 issues

### ISSUE THREAD

**Issue by djmtype** [AMoreaux/Sketch-Icons#32]
After updating to Sketch v49, this plugin will no longer apply a mask. It doesn't allow me to choose a color symbol as the mask color from the same document or any library even though the libraries are listed in the dropdown. 

After the import has finished some of the icons are not sized properly – they remain enormous in size.

[Screenshot](https://cloudup.com/cIWR8-0FUdj)

**Comment by djmtype** [comment]
I was able to apply a mask to the icons. But, first I had to choose a color from the color picker. Then, run the Sketch Icons command to replace mask color. 

Regardless, there is no way of assigning a color symbol to be the mask color – it appears broken in Sketch 49.

**Comment by AMoreaux** [comment]
Hi @djmtype, we are working to resolve this issue. Thanks for the report 😉
