### ISSUE TITLE
"Import Icons..." does not do anything (Sketch 49.1)

### ISSUE THREAD

**Issue by uicoded** [AMoreaux/Sketch-Icons#34]
**Sketch 49.1 (51147), Sketch-Icons 3.0.14**
Selecting: "Plugins->Sketch Icons->Import Icons..." does not perform any action.
![sketch icons not working](https://user-images.githubusercontent.com/124282/37611746-945f7bfc-2b79-11e8-94c5-09024947de51.gif)

Expected behavior: Configure your import modal should open.

**Comment by AMoreaux** [comment]
What version of osx do you use ?

**Comment by twitcher07** [comment]
I seem to be having this same issue. 
https://www.dropbox.com/s/by6bgv415c10r3f/sketch%20icons%20plugin_720.mov?dl=0

macOS version 10.11.6
Sketch version: 49.1
Sketch-icon version: 3.0.14

**Comment by AMoreaux** [comment]
Sorry but Sketch Icons is not compatible with MacOS El Capitan.

**Comment by twitcher07** [comment]
Ah ok. I've updated to High Sierra and now it works. Thanks!
