### ISSUE TITLE
Fail to import some Material Design Icons with mask

### ISSUE THREAD

**Issue by wrongch** [AMoreaux/Sketch-Icons#36]
I want to import material design icons, and add the mask.

Most icons  are perfect, except some icons like  ic_battery_80， ic_battery_50  series.
when imported , all the same, like the ic_battery_full.

**Comment by AMoreaux** [comment]
Hi @wrongch . To apply a color on icons you need to use masks. So the color is applied on one shape composed by all shapes of the icon. You can't apply more than one color on a single icon. As you can see there is more than one color on ic_battery series. 😕
