### ISSUE TITLE
Plugin menu doesn't appear

### ISSUE THREAD

**Issue by Weissenberger13** [AMoreaux/Sketch-Icons#37]
When I click on an option, the popup box doesnt appear so essentially can't use the plugin.

**Comment by AMoreaux** [comment]
What version of OSX and sketch do you use ?

**Comment by dnsorlov** [comment]
Same here, no reaction on any interactions with plugin menu, OSX 10.12.3, sketch 49.3.

**Comment by Weissenberger13** [comment]
sketch 49.3, OSX 10.12.1

**Comment by AMoreaux** [comment]
The oldest version I could test is sketch 49.3 and OSX 10.12.6. 
Try again by disabling the other plugin. Sometimes there are conflicts between plugins.
Moreover can you send me a screenshot of your console please. (See my message here: #19 )

**Comment by Weissenberger13** [comment]
I updated my osx to the 10.12.6 and it works now
