### ISSUE TITLE
Apply color mask doesn't apply mask

### ISSUE THREAD

**Issue by kweamod** [AMoreaux/Sketch-Icons#38]
When I try to apply a Color mask via Symbol it just colorizes the shapes in the symbol directly and doesn't add the color as a mask. So I can't change the color in the overrides.

**Comment by AMoreaux** [comment]
You use outline icons ? Try to check "stroke to fill" in settings. It will transform border to fill and you will be able to use color as mask.

**Comment by kweamod** [comment]
@AMoreaux Thanks for your reply. It works when I use the "Convert to Outlines" functionality of Sketch. However the checking of "stroke to fill" seems to have no effect.

**Comment by AMoreaux** [comment]
@kweamod Could you send me one or two icons with which you have tested the function "stroke to fill" so that I can correct it.

**Comment by kweamod** [comment]
Sure thing. @AMoreaux 

[stroke-to-fill-test.sketch.zip](https://github.com/AMoreaux/Sketch-Icons/files/1995712/stroke-to-fill-test.sketch.zip)

**Comment by misterchibi** [comment]
I have the same problem since I update to Sketch 50.

**Comment by AMoreaux** [comment]
I’m working on it. I will publish a patch on a few days. 🙂

**Comment by kweamod** [comment]
@AMoreaux Works! Thank you for the update! :)

**Comment by AMoreaux** [comment]
Thanks 🙂 let me know if you find other bugs. 😉
