### ISSUE TITLE
"Import icons..."  modal dialog lack of all input element

### ISSUE THREAD

**Issue by brrr** [AMoreaux/Sketch-Icons#45]
First of all, thank you for the greet work!
Alter I click "Import icons..." menu button, a modal dialog shows ,but not completely.
It seems all input elements in the modal dialog are missing. See attachment below.

I've tried reinstall the plugin (manually or via Runner),disable all other plugins, but neither works

OS ver:10.13.5 High Sierra
Sketch ver:45.2
stitch-icons ver:4.0.5

<img width="423" alt="image" src="https://user-images.githubusercontent.com/775351/42440301-ef72393c-8397-11e8-8212-e799c36d5513.png">

**Comment by brrr** [comment]
I update sketch to 49, it works fine now.
It seems that this plugin not support sketch 45
please close this issue

**Comment by valentinchrt** [comment]
Thanks @brrr for your feedback!
