### ISSUE TITLE
Not working on Sketch 52

### ISSUE THREAD

**Issue by mkstvnsn** [AMoreaux/Sketch-Icons#48]
Trying to import fonts but nothing happens. I'm sure you're aware.

**Comment by valentinchrt** [comment]
Hi @mkstvnsn!

Thanks for your feedback. 

Indeed, we are aware of the problem. We are currently working on it, we should roll out a new version in the coming weeks. We are doing our best to solve the problem as soon as possible.

Val

**Comment by mkstvnsn** [comment]
Awesome @valentinchrt! Was wondering if it was just me. Thanks for the great plugin!

**Comment by aaronsleeper** [comment]
i can't believe i just found this plugin. would've saved me so much time lol and now it doesn't work in 52. definitely keeping an eye on this. hope it's working soon. thank you soooooo much for your work!!!!
