### ISSUE TITLE
replace mask with style

### ISSUE THREAD

**Issue by preciselykem** [AMoreaux/Sketch-Icons#49]
Now that sketch 51 supports layer style overrides, I'd like to move away from masks and into styles. Would love for this plugin to let me apply a layer style to all icons.

**Comment by valentinchrt** [comment]
Hi @preciselykem,

Thanks for your suggestion!
To be honest, we are currently working on this feature. It will be implemented in the next few weeks. 

We are doing our best to edit the plugin as soon as possible. 😉

Val
