### ISSUE TITLE
Some SVG files will turn up blank

### ISSUE THREAD

**Issue by kellyvuijst** [AMoreaux/Sketch-Icons#5]
Some icons in my set will turn up as blank canvasses. I dropped some example files below that are not showing up. For the set below, only the milk, pig and chicken will show, the rest are blank artboards with nothing inside.

![screen shot 2018-01-11 at 12 45 17](https://user-images.githubusercontent.com/4254711/34824082-53f10508-f6cd-11e7-974c-228ccc77bdc8.png)

[my-icons-collection-23.zip](https://github.com/AMoreaux/Sketch-Icons/files/1622364/my-icons-collection-23.zip)

**Comment by valentinchrt** [comment]
Thank you @kellyvuijst!

We'll take a look 👀

**Comment by AMoreaux** [comment]
hi @kellyvuijst, thanks for your feedback, I found the problem. I will fixed it in the next version.

**Comment by AMoreaux** [comment]
It's fixed in the latest version. 🙂
