### ISSUE TITLE
Request: Simple creation of masked icons

### ISSUE THREAD

**Issue by jansemka** [AMoreaux/Sketch-Icons#6]
Thanks for this one! I had a similar idea for a plugin to generate these icons. The huge downside is, i take a lot of stroked icons and they need to be converted to shapes so that they work as a mask. Another downside was the creation of the symbol itself. I would recommend/had the following workflow concept in my mind:

1. Drag n drop you icon/icons (I use iconjar/nucleo)
2. Select the icons
3. Shortcut to create the symbol including the masking of it. A popup appears with all necessary settings
4. Push it to the symbol page

In your workflow i have to create the stroke to shape and also the artboard itself. In most of the projects i gather the icons while i am working on the project. I am not importing 10+ icons at once.

**Comment by valentinchrt** [comment]
Hey @jansemka,

Wow, thank you for your feedback!
To be honest, we know about strokes, we're working on that right now.

**Here is our global roadmap:**
**Release 4.0:** 
Ability to apply a color on stroked icons. If the applied color comes from a library, we will apply a color to the border. The icon will not be dynamic!
**Release 5.0:** 
When a color is applied to a stroked icon, it will be automatically converted from stroke to fill. We will also add a settings panel for more customization!

If you want to improve the plugin, don't hesitate to make a pull request! There is already a v4 branch. We would love it :)

Thanks again!
