### ISSUE TITLE
Remove Black Fill from Dynamic Color Masked Icons

### ISSUE THREAD

**Issue by edwardsdesign** [AMoreaux/Sketch-Icons#7]
When generating an icon with a dynamic color mask allow an option to remove the black fill on the vector shape. Currently, if the dynamic color mask has alpha transparency, it is obscured by the black fill and requires the user to have to

1. Generate icons without color mask
2. Select all icons and remove black fill
3. update selected icons with dynamic color mask

Remove fill option would allow user to just generate icons without black fill.

**Comment by AMoreaux** [comment]
Hi @edwardsdesign  thanks for the feedback, we are working on a plugin that will generate a color library with a color picker. I think it's a better solution to make two plugins and dissociate features.

**Comment by valentinchrt** [comment]
Thanks for your explanation @edwardsdesign!
We take note of it. This will be fixed in the next release! 🎉
