### ISSUE TITLE
Create symbol from Color Picker Color Source

### ISSUE THREAD

**Issue by edwardsdesign** [AMoreaux/Sketch-Icons#8]
Add option to to create a symbol from the selected color picker color.

This is more of a nice-to-have when generating large icon libraries. If you are allowing the user to pick a color, giving them the ability to convert that picked color into a dynamic symbol in the same step would compliment the plugin's intended functionality.

**Comment by AMoreaux** [comment]
Hi @edwardsdesign thanks for the feedback, we are working on a plugin that will generate a color library with a color picker. I think it's a better solution to make two plugins and dissociate features.
