### ISSUE TITLE
Ability to append a path structure to the name.

### ISSUE THREAD

**Issue by sqwear** [AMoreaux/Sketch-Icons#9]
More a feature request, but can the ability to add "path/to/symbol" structuring during the creation of the symbols?

**Comment by AMoreaux** [comment]
Hi @sqwear. You speak about the path of the file system ? If you want manage your icons by name. I suggest to use the plugin "rename it". Look the bonus tips in the medium article: https://blog.prototypr.io/introducing-sketch-icons-2074d9dc9ed2

**Comment by sqwear** [comment]
@AMoreaux thanks man for the tip. Awesome plugin!!!
